// Code generated by Kitex v0.14.1. DO NOT EDIT.
package itemservice

import (
	server "github.com/cloudwego/kitex/server"
	item "iflytek.com/weipan4/learn-go/grpc/kitex/shop/kitex_gen/item"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler item.ItemService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler item.ItemService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
